/*

(c) 2016 Copyright Vaclav2016 https://github.com/vaclav2016, jabber id vaclav2016@jabber.cz

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include<stdlib.h>
#include<stdio.h>
#include<stdint.h>
#include"safegc.h"

#define MIN_FREE_BLK 128

#define SIGNATURE 0x1234

#pragma pack(push, 1)
typedef enum { BUSY, FREE } Type;

struct MemBlk {
	size_t size;
	uint16_t sign;
	Type type;
	struct MemBlk *next;
};
#pragma pack(pop)

#define MEM_BLK_SIZE sizeof(struct MemBlk)

struct MemBlk *first;
size_t gc_memsize;

void gc_init(size_t size) {
	first = malloc(size);
	first->type = FREE;
	first->sign = SIGNATURE;
	first->size = size - MEM_BLK_SIZE;
	first->next = NULL;
	gc_memsize = size;
}

void gc_done() {
	free(first);
}

void *gc_malloc(size_t size) {
	struct MemBlk *f = first;
	struct MemBlk *n;
	void *result = NULL;
	size_t fsize;
	size_t nsize;
	if(size % MIN_FREE_BLK != 0) {
		size = (size / MIN_FREE_BLK + 1) * MIN_FREE_BLK;
	}
	while(f != NULL) {
		if((f->type == FREE) && (f->size > size + 2 * MEM_BLK_SIZE + MIN_FREE_BLK)) {
			result = ((void*)f) + MEM_BLK_SIZE;

			fsize = f->size;
			nsize = fsize - (MEM_BLK_SIZE + size);
			fsize = size;
			n = ((void *)f) + MEM_BLK_SIZE + size;
			n->size = nsize;
			n->type = FREE;
			n->sign = SIGNATURE;
			n->next = f->next;

			f->size = fsize;
			f->next = n;
			f->type = BUSY;
			break;
		}
		f = f->next;
	}
	if(result == NULL) {
		printf("Not enought memory. Can't alloce %i byte(s)\n", size);
	}
	return result;
}

void gc_free(void *ptr) {
	struct MemBlk *p;
	struct MemBlk *n = (ptr - MEM_BLK_SIZE);
	if(n->sign != SIGNATURE) {
		fprintf(stderr, "free(%x) - invalid pointer.\n", ((void*)n) - ((void *)first));
		return;
	}
	n->type = FREE;
	n = first;
	p = NULL;
	while(n != NULL) {
		if((p != NULL) && (p->type == FREE) && (n->type == FREE)) {
			p->size += n->size + MEM_BLK_SIZE;
			p->next = n->next;
			n = p;
		}
		p = n;
		n = n->next;
	}
}

int gc_isempty() {
	return (first->next == NULL) && (first->type == FREE) && (first->size == (gc_memsize - MEM_BLK_SIZE));
}

void gc_dump() {
	struct MemBlk *p = first;
	if(gc_isempty()) {
		return;
	}
	printf("Memory leaks detected!\n");
	printf("- Memory dump ---------------------------\n");
	printf("MEM_BLK_SIZE = %x\tMIN_FREE_BLK = %x\n", MEM_BLK_SIZE, MIN_FREE_BLK);
	printf("| %10s | %5s | %8s |\n", "ADDR", "STATE", "SIZE");
	while(p != NULL) {
		printf("| %10x | %5s | %8x |\n", (size_t)( ((void *)p) - ((void *)first) ), (p->type == FREE ? "FREE" : "BUSY"), p->size);
		p = p->next;
	}
}
